"""empty message

Revision ID: c75b896e9013
Revises: 
Create Date: 2022-12-14 15:41:36.107475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75b896e9013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('goodname', sa.String(length=100), nullable=False),
    sa.Column('goodproduce', sa.String(length=100), nullable=False),
    sa.Column('goodvalue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('storename', sa.String(length=100), nullable=False),
    sa.Column('storeplace', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('storge',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('storgename', sa.String(length=100), nullable=False),
    sa.Column('storgeproduce', sa.String(length=100), nullable=False),
    sa.Column('storgevalue', sa.Float(), nullable=False),
    sa.Column('storgenumber', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('requeststorgeid', sa.BigInteger(), nullable=False),
    sa.Column('requeststoreid', sa.BigInteger(), nullable=False),
    sa.Column('requestnumber', sa.BigInteger(), nullable=False),
    sa.Column('requestdealnumber', sa.BigInteger(), nullable=True),
    sa.Column('requesttime', sa.String(length=100), nullable=False),
    sa.Column('requestdealtime', sa.String(length=100), nullable=True),
    sa.Column('requeststatus', sa.Boolean(), nullable=True),
    sa.Column('deliverstatus', sa.Boolean(), nullable=True),
    sa.Column('deliverdealtime', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['requeststoreid'], ['store.id'], ),
    sa.ForeignKeyConstraint(['requeststorgeid'], ['storge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('salestorgeid', sa.BigInteger(), nullable=False),
    sa.Column('salestoreid', sa.BigInteger(), nullable=False),
    sa.Column('salenumber', sa.BigInteger(), nullable=False),
    sa.Column('saletime', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['salestoreid'], ['store.id'], ),
    sa.ForeignKeyConstraint(['salestorgeid'], ['storge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('staffname', sa.String(length=100), nullable=False),
    sa.Column('stafftype', sa.Enum('售货员', '商店经理', '管理员'), nullable=True),
    sa.Column('staffsex', sa.Enum('男', '女'), nullable=True),
    sa.Column('staffsalary', sa.String(length=100), nullable=False),
    sa.Column('staffworkplace', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['staffworkplace'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('storgestore',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('storgestoregoodid', sa.BigInteger(), nullable=False),
    sa.Column('storgestoreid', sa.BigInteger(), nullable=False),
    sa.Column('storgestoretime', sa.String(length=100), nullable=False),
    sa.Column('storgestorenumber', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['storgestoregoodid'], ['storge.id'], ),
    sa.ForeignKeyConstraint(['storgestoreid'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('storgestore')
    op.drop_table('staff')
    op.drop_table('sale')
    op.drop_table('request')
    op.drop_table('storge')
    op.drop_table('store')
    op.drop_table('goods')
    # ### end Alembic commands ###
